[project]
name = "inventorycompliancereporter"
version = "0.2.0"
description = "Automated inventory compliance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pytest>=9.0.2",
    "tkinterweb>=3.24",
    "tksheet>=7.5.19",
    "nicemail>=0.2.1"
]



[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
icr = "icr.app:app_main"
