[project]
name = "inventorycompliancereporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pytest>=9.0.2",
    "tkinterweb>=3.24",
]



[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
icr = "icr.app:app_main"
